#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...

export PATH=$HOME/bin:$HOME/.composer/vendor/bin:/usr/local/bin:$PATH
