#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...


bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^r' history-incremental-search-backward

vim_ins_mode="%{$fg[cyan]%}[Insert]%{$reset_color%}"
vim_cmd_mode="%{$fg[green]%}[Normal]%{$reset_color%}"
vim_mode=$vim_ins_mode

function zle-keymap-select {
  vim_mode="${${KEYMAP/vicmd/${vim_cmd_mode}}/(main|viins)/${vim_ins_mode}}"
  zle reset-prompt
}
zle -N zle-keymap-select

function zle-line-finish {
  vim_mode=$vim_ins_mode
}
zle -N zle-line-finish

# Fix a bug when you C-c in CMD mode and you'd be prompted with CMD mode indicator, while in fact you would be in INS mode
# Fixed by catching SIGINT (C-c), set vim_mode to INS and then repropagate the SIGINT, so if anything else depends on it, we will not break it
# Thanks Ron! (see comments)
function TRAPINT() {
  vim_mode=$vim_ins_mode
  return $(( 128 + $1 ))
}

#
# Aliases
#

source $HOME/dotfiles/zsh/alias.zsh
