#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

source $HOME/dotfiles/zsh/alias.zsh
