# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401
from qutebrowser.config.config import ConfigContainer  # noqa: F401

config = config  # type: ConfigAPI # noqa: F821 pylint: disable=E0602,C0103
config.load_autoconfig(False)
c = c  # type: ConfigContainer # noqa: F821 pylint: disable=E0602,C0103

c.qt.force_platform = "wayland"
c.qt.highdpi = True
c.tabs.position = "left"

config.set("downloads.location.directory", "~/Downloads")
config.set("downloads.location.prompt", True)

config.set(
    "aliases",
    {
        "q": "close",
        "qa": "quit",
        "w": "session-save",
        "wq": "quit --save",
        "wqa": "quit --save",
        "bn": "tab-next",
        "bp": "tab-prev",
    },
)

config.bind("u", "back")
config.bind("<Ctrl-r>", "forward")

config.bind("<Ctrl-l>", "tab-next")
config.bind("<Ctrl-h>", "tab-prev")

config.set("content.cookies.accept", "all", "chrome-devtools://*")
config.set("content.cookies.accept", "all", "devtools://*")

config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0",
    "https://accounts.google.com/*",
)
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36",
    "https://*.slack.com/*",
)

config.set("content.images", True, "chrome-devtools://*")
config.set("content.images", True, "devtools://*")
config.set("content.javascript.enabled", True, "chrome-devtools://*")
config.set("content.javascript.enabled", True, "devtools://*")
config.set("content.javascript.enabled", True, "chrome://*/*")
config.set("content.javascript.enabled", True, "qute://*/*")
config.set(
    "content.local_content_can_access_remote_urls",
    True,
    "file:///home/edwlarkey/.local/share/qutebrowser/userscripts/*",
)
config.set(
    "content.local_content_can_access_file_urls",
    False,
    "file:///home/edwlarkey/.local/share/qutebrowser/userscripts/*",
)

config.source("gruvbox.py")
