# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
from platform import system
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401
from qutebrowser.config.config import ConfigContainer  # noqa: F401

config = config  # type: ConfigAPI # noqa: F821 pylint: disable=E0602,C0103
config.load_autoconfig(False)
c = c  # type: ConfigContainer # noqa: F821 pylint: disable=E0602,C0103

leader = "\\"
localleader = " "

# c.qt.force_platform = "wayland"
c.qt.highdpi = True
c.auto_save.interval = 15000  # milliseconds
c.auto_save.session = True
c.session.lazy_restore = True
c.tabs.position = "left"
c.colors.webpage.preferred_color_scheme = "light"
c.completion.shrink = True
c.completion.use_best_match = True
c.downloads.position = "bottom"
c.downloads.remove_finished = 10000
c.statusbar.widgets = ["progress", "keypress", "url", "history"]
c.scrolling.bar = "always"
c.content.default_encoding = "utf-8"
c.content.pdfjs = True
c.editor.command = [
    "tmux",
    "new-window",
    "trap 'tmux wait-for -S qutebrowser-{file}' 0 && nvim -c 'normal {line}G{column0}l' {file}",
    ";",
    "wait-for",
    "qutebrowser-{file}",
]
c.input.insert_mode.auto_load = True
c.tabs.select_on_remove = "next"
c.tabs.title.format_pinned = "{index}: {audio}{current_title}"

c.completion.web_history.max_items = 10000

c.content.javascript.clipboard = "access"


config.set("fonts.statusbar", "14pt default_family")
config.set("fonts.completion.entry", "12pt default_family")

if system() == "Darwin":
    config.set("fonts.tabs.selected", "16pt default_family")
    config.set("fonts.tabs.unselected", "16pt default_family")

config.set("downloads.location.directory", "~/Downloads")
config.set("downloads.location.prompt", True)

config.set(
    "aliases",
    {
        "q": "close",
        "qa": "quit",
        "w": "session-save",
        "wq": "quit --save",
        "wqa": "quit --save",
        "bn": "tab-next",
        "bp": "tab-prev",
        "bd": "tab-close",
        "bm": "open -t qute://bookmarks/",
        "proc": "open -t ;; process",
        "mess": "open -t qute://log/",
    },
)

config.bind("<Ctrl+n>", "completion-item-focus --history next", mode="command")
config.bind("<Ctrl+p>", "completion-item-focus --history prev", mode="command")

config.bind("u", "back")
config.bind("<Ctrl-r>", "forward")
config.bind("x", "forward")
config.bind("z", "back")
config.bind("..", "forward")
config.bind(",,", "back")
config.bind(f"{leader}m", "open -t qute://bookmarks/")

config.bind("<Ctrl-l>", "tab-next")
config.bind("<Ctrl-h>", "tab-prev")

config.bind("<Ctrl-t>", "config-cycle -t tabs.position top left")
config.bind("t/", "cmd-set-text -s :tab-select")

config.bind("<Ctrl-Shift-r>", "restart")
config.bind("<Ctrl-Shift-c>", "config-source")

qute_pass = "qute-pass -d 'wofi --dmenu' --username-target secret --username-pattern 'username: (.+)'"
config.bind(f"{leader}p", f"spawn --userscript {qute_pass}", mode="insert")
config.bind(f"{leader}P", f"spawn --userscript {qute_pass} .", mode="insert")
config.bind(
    f"{leader}u", f"spawn --userscript {qute_pass} --username-only", mode="insert"
)
config.bind(
    f"{leader}U", f"spawn --userscript {qute_pass} --password-only", mode="insert"
)

config.set("content.cookies.accept", "all", "chrome-devtools://*")
config.set("content.cookies.accept", "all", "devtools://*")

config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0",
    "https://accounts.google.com/*",
)
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
    "https://*.slack.com/*",
)

# Google meet
config.set("content.notifications.enabled", True, "https://meet.google.com")
config.set("content.media.audio_video_capture", True, "https://meet.google.com")
config.set("content.media.audio_capture", True, "https://meet.google.com")
config.set("content.media.video_capture", True, "https://meet.google.com")
config.set("content.desktop_capture", True, "https://meet.google.com")

config.set("content.local_content_can_access_remote_urls", True)
config.set("content.images", True, "chrome-devtools://*")
config.set("content.images", True, "devtools://*")
config.set("content.images", True, "file://*")
config.set("content.javascript.enabled", True, "chrome-devtools://*")
config.set("content.javascript.enabled", True, "devtools://*")
config.set("content.javascript.enabled", True, "chrome://*/*")
config.set("content.javascript.enabled", True, "qute://*/*")
config.set(
    "content.local_content_can_access_remote_urls",
    True,
    "file:///home/edwlarkey/.local/share/qutebrowser/userscripts/*",
)
config.set(
    "content.local_content_can_access_file_urls",
    False,
    "file:///home/edwlarkey/.local/share/qutebrowser/userscripts/*",
)

# config.source("gruvbox.py")
