#!/usr/bin/env bash
#
# Sets up my dotfiles
#

set -e

echo ''

info () {
    printf "\r\033[2K  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

user () {
    printf "\r\033[2K  [ \033[00;33m##\033[0m ] %s\n" "$1"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
    echo ''
    exit
}

setup_gitconfig () {
    info 'Setup git'

    if [ -f "$HOME/.local.gitconfig" ]; then
      info "$HOME/.local.gitconfig found, deleting"
      rm "$HOME/.local.gitconfig"
    fi

    mkdir -p $HOME/.config/git
    mkdir -p $HOME/git
    ln -nfs "$HOME/dotfiles/git/gitconfig" "$HOME/.gitconfig"
    git config --file "$HOME/.config/git/config" commit.template "~/dotfiles/git/git-commit-template"
    ln -nfs "$HOME/dotfiles/git/$git_location-config" "$HOME/.config/git/config"

    success 'Git setup complete'
}

link_files () {
    info 'Linking files'
    ln -nfs "$HOME/dotfiles/vim" "$HOME/.vim"
    ln -nfs "$HOME/dotfiles/vim/vimrc" "$HOME/.vimrc"
    success 'vim linked'
    ln -nfs "$HOME/dotfiles/nvim" "$HOME/.config/nvim"
    mkdir -p "$HOME/.local/share/nvim/session"
    success 'nvim linked'
    ln -nfs "$HOME/dotfiles/bin" "$HOME/bin"
    success 'bin linked'
    ln -nfs "$HOME/dotfiles/tmux/tmux.conf" "$HOME/.tmux.conf"
    ln -nfs "$HOME/dotfiles/tmux" "$HOME/.tmux"
    success 'tmux linked'
    ln -nfs "$HOME/dotfiles/aerc" "$HOME/.config/aerc"
    success 'aerc linked'
    ln -nfs "$HOME/dotfiles/zsh" "$HOME/.zsh"
    ln -nfs "$HOME/dotfiles/zsh/zlogin" "$HOME/.zlogin"
    ln -nfs "$HOME/dotfiles/zsh/zlogout" "$HOME/.zlogout"
    ln -nfs "$HOME/dotfiles/zsh/zprofile" "$HOME/.zprofile"
    ln -nfs "$HOME/dotfiles/zsh/zshrc" "$HOME/.zshrc"
    ln -nfs "$HOME/dotfiles/zsh/zshenv" "$HOME/.zshenv"
    success 'zsh linked'
    ln -nfs "$HOME/dotfiles/xinitrc" "$HOME/.xinitrc"
    success 'xinitrc config linked'
    ln -nfs "$HOME/dotfiles/ghostty" "$HOME/.config/ghostty"
    success 'ghostty config linked'
    ln -nfs "$HOME/dotfiles/alacritty" "$HOME/.config/alacritty"
    success 'alacritty config linked'
    ln -nfs "$HOME/dotfiles/starship.toml" "$HOME/.config/starship.toml"
    success 'starship config linked'
    ln -nfs "$HOME/dotfiles/sway" "$HOME/.config/sway"
    success 'sway config linked'
    ln -nfs "$HOME/dotfiles/hypr" "$HOME/.config/hypr"
    success 'hyprland config linked'
    ln -nfs "$HOME/dotfiles/mako" "$HOME/.config/mako"
    success 'mako config linked'
    ln -nfs "$HOME/dotfiles/waybar" "$HOME/.config/waybar"
    success 'waybar config linked'
    ln -nfs "$HOME/dotfiles/wofi" "$HOME/.config/wofi"
    success 'wofi config linked'
    ln -nfs "$HOME/dotfiles/karabiner" "$HOME/.config/karabiner"
    success 'karabiner config linked'
}

make_dirs () {
    info 'Creating directories'
    mkdir -p "$HOME/.config"
    mkdir -p "$HOME/.config/git"
    mkdir -p "$HOME/.vim-backup"
    mkdir -p "$HOME/.vim-undo"
    mkdir -p "$HOME/.vim-swap"
    success 'vim dirs created'
    mkdir -p "$HOME/git"
    success "$HOME/git created"
}

pull_submodules () {
    cd "$HOME/dotfiles" && git submodule init && git submodule update
    git submodule update --init --recursive
}

install_vim_plugins () {
    info 'Install Vim plugins'
    vim +PlugInstall +qall
    success 'Plugins installed'
}

# setup_gitconfig
PS3='Set up for which location: '
options=("Home" "Work" "Other" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Home")
            info "Setting up for Home"
            git_location=home
            break
            ;;
        "Work")
            info "Setting up for Work"
            git_location=work
            break
            ;;
        "Quit")
            exit 1
            ;;
        *) echo invalid option;;
    esac
done

make_dirs
setup_gitconfig
link_files
pull_submodules
# install_vim_plugins
