[aws]
symbol = "aws "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled =  true

[directory]
truncate_to_repo = false
style = "bright-yellow"

[git_branch]
symbol = ""
style = "cyan"

[git_status]
style = "red"
modified_count.enabled = true
modified_count.style = "red"
modified.style = "red"
modified.vaule = "~"
stashed_count.enabled = true
stashed_count.style = "red"
stashed.style = "red"
stashed.vaule = "$"
staged_count.enabled = true
staged_count.style = "green"
staged.style = "green"
staged.vaule = "+"
deleted_count.enabled = true
deleted_count.style = "red"
deleted.style = "red"
deleted.vaule = "✘"
untracked_count.enabled = true
untracked_count.style = "red"
untracked.style = "red"
untracked.vaule = "?"
renamed_count.enabled = true
renamed_count.style = "red"
renamed.style = "red"
renamed.vaule = "»"

[golang]
symbol = "go "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
