[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = ""
[aws.profile_aliases]
AdministratorAccess = 'Admin'

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled =  true

[directory]
truncate_to_repo = false
style = "bright-yellow"

[git_branch]
symbol = ""
style = "cyan"

[git_status]
up_to_date = "✓"
untracked = "?"
# stashed = "$"
modified = "~"
staged = '[++\($count\)](green)'
renamed = "»"
deleted = "✘"

[golang]
symbol = "go "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[kubernetes]
# Custom style doesn't override green here for some reason
# format = '[$context \($namespace\)](green) '
disabled = false
symbol = ""
style = "green"
contexts = [
  { context_pattern = ".*production.*", style = "red", symbol = "󰀩 "},
]

[gcloud]
format = 'on [$symbol($project)]($style) '
symbol = '️🇬️ '

[memory_usage]
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "
