[aws]
symbol = "aws "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled =  true

[directory]
truncate_to_repo = false
style = "bright-yellow"

[git_branch]
symbol = ""
style = "cyan"

[git_status]
style = "red"
modified.enabled = true
modified.style = "red"
modified.vaule = "~"
stashed.enabled = true
stashed.style = "red"
stashed.vaule = "$"
staged.enabled = true
staged.style = "green"
staged.vaule = "+"
deleted.enabled = true
deleted.style = "red"
deleted.vaule = "✘"
untracked.enabled = true
untracked.style = "red"
untracked.vaule = "?"
renamed.enabled = true
renamed.style = "red"
renamed.vaule = "»"

[golang]
symbol = "go "

[hg_branch]
symbol = " "

[java]
symbol = " "

[kubernetes]
format = 'on [☸️ $context \($namespace\)](green) '
disabled = false

[kubernetes.context_aliases]
"production" = "***PRODUCTION***"

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
