" Edward Larkey's vimrc
"
" Snippets were taken from many places over the years.
"
" Clear autocmds
autocmd!

set nocompatible    " Use Vim settings, rather than Vi settings

filetype off        "required
let g:ale_completion_enabled = 0

" =============================================================================
" Plugins {{{1
" =============================================================================
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'plasticboy/vim-markdown'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'dense-analysis/ale'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'rhysd/vim-lsp-ale'
Plug 'morhetz/gruvbox'
Plug 'airblade/vim-gitgutter'
Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'edwlarkey/vim-toggler'
" Plug 'vim/colorschemes'
Plug 'romainl/Apprentice'
Plug 'sonph/onehalf', {'rtp': 'vim/'}
Plug 'lervag/vimtex', { 'for': 'tex' }
Plug 'zhimsel/vim-stay'
Plug 'junegunn/vim-peekaboo'

"""""""""""""""""""""""""""""""""""""""
" Syntax Plugins
"""""""""""""""""""""""""""""""""""""""
Plug 'edwlarkey/vim-textcal'

call plug#end()

if !empty(glob("~/.vim/functions.vim"))
  source ~/.vim/functions.vim
endif

" =============================================================================
" Snippets {{{1
" =============================================================================
" Read an empty HTML template and move cursor to title
nnoremap ,html :-1read $HOME/.vim/templates/html<CR>4jwf>a


" =============================================================================
" General Config {{{1
" =============================================================================

set encoding=utf-8 nobomb " Use UTF-8 without BOM

" Use <SPACE> as leader
let mapleader=" "
let maplocalleader=","

filetype plugin indent on

set backspace=indent,eol,start                                               " Backspace over everything in insert mode
set tags=./tags,tags;                                                        " Tags
set spellfile+=~/Dropbox/spell/en.utf-8.add                                  " Spelling file
set hidden                                                                   " Allow unsaved background buffers and remember marks/undo for them
set autoread                                                                 " Auto-reload buffers when files are changed on disk
set nojoinspaces                                                             " Use only 1 space after ' . ' when joining lines instead of 2
set nostartofline                                                            " Don't reset cursor to start of line when moving around
set wildmenu                                                                 " Make tab completion for files/buffers act like bash
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem          " Disable output and VCS files
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz                      " Disable archive files
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/* " Ignore bundler and sass cache
set wildignore+=*/node_modules/*                                             " Ignore node modules

" Disable temp and backup files
set wildignore+=*.swp,*~,._*
set wildignore=*.bak,*.pyc,*.class

""
"" Backup, swap, undo
""
set backup
set backupdir=~/.vim-backup//
set directory=~/.vim-swap//
set undofile
set undodir=~/.vim-undo//
set writebackup

""
"" Search
""
set showmatch  " Show matches
set hlsearch   " Highlight searches
set incsearch  " Highlight dynamically as pattern is typed
set ignorecase " Make searches case-insensitive...
set smartcase  " ...unless they contain at least one uppercase character

if executable("ag")
  set grepprg=ag\ --nogroup\ --nocolor\ --ignore-case\ --column
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

" =============================================================================
" Appearance {{{1
" =============================================================================

" set cursorline    " Highlight current line
" set t_Co=256      " 256 colors
set scrolloff=5     " Keep more buffer context when scrolling
set cmdheight=1     " Set command line height (default)
set title           " Show the filename in the window titlebar
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
set noerrorbells    " Disable error bells
set vb t_vb=        " Disable bells
set number          " Show line numbers
" set relativenumber  " Relative numbering
syntax on
set viewoptions=cursor,folds,slash,unix

""
"" Statusline
""

set noruler
set laststatus=2
set statusline=
set statusline+=%t\                             " tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, " file encoding
set statusline+=%{&ff}]\                        " file format
set statusline+=%y\                             " filetype
set statusline+=%h\                             " help file flag
set statusline+=%m\                             " modified flag
set statusline+=%r\                             " read only flag
set statusline+=%=                              " left/right separator
set statusline+=line:%l/%L\                     " cursor line/total lines
set statusline+=col:%c\                         " cursor column
set statusline+=\ %P                            " percent through file

""
"" Colorscheme and colorcolumn
""

if !empty(glob("~/light"))
  set background=light
  colorscheme onehalflight
else
  set background=dark
    " Gruvbox
    let g:gruvbox_contrast_light = 'hard'
    let g:gruvbox_contrast_dark = 'soft'
    colorscheme gruvbox
endif 

" dont display color column if it doesn't support it
if v:version > 703
  let &colorcolumn="80,".join(range(120,999),",")
endif

""
"" Whitespace
""

" Indentation
set expandtab     " Tab in insert mode will produce spaces
" set tabstop=2     " Width of a tab
set shiftwidth=2  " Width of reindent operations and auto indentation
set softtabstop=2 " Set spaces for tab in insert mode
set autoindent    " Enable auto indentation
set copyindent    " Copy indentation from source
set smarttab
set nowrap        " Don't wrap lines

" Invisible characters
set list
set listchars=tab:>·,trail:·,extends:#,nbsp:.

" =============================================================================
" Registers
" =============================================================================

" Use the OS clipboard by default
" set clipboard=unnamed

" Copy to unnamed register
map <leader>y "*y

" Paste from unnamed register and fix indentation
nmap <leader>p o<ESC>"*pV`]=
nmap <leader>P o<ESC>"*p

" Delete to the blackhole register
" nnoremap <leader>x "_x
" nnoremap <leader>d "_dd

" inoremap <s-tab> <c-x><c-o>

" =============================================================================
" General Keybindings
" =============================================================================

" stop the command window
map q: :q

" Joining with indents is useless - instead join and delete spaces
nnoremap gJ Jdiw

" C-h and C-l keys change buffers in all modes
noremap <C-h> <Esc>:bp<CR>
inoremap <C-h> <Esc>:bp<CR>
nnoremap <C-h> <Esc>:bp<CR>
vnoremap <C-h> <Esc>:bp<CR>

noremap <C-l> <Esc>:bn<CR>
inoremap <C-l> <Esc>:bn<CR>
nnoremap <C-l> <Esc>:bn<CR>
vnoremap <C-l> <Esc>:bn<CR>

" quick vimrc editing
" The autocmd should be in another secion, but I like it all together
:nnoremap <leader>v :e $MYVIMRC<cr>
autocmd BufWritePost .vimrc source %

" Move item to bottom and append timestamp
nnoremap <leader>mv ddGpA completed:<C-R>=strftime("%Y-%m-%d %H:%M")<CR><Esc>``

" Make
nmap <leader>m :Make<CR>

" go to next line on screen
nnoremap j gj
nnoremap k gk

" Disable arrow keys
noremap <up> <nop>
nnoremap <up> <nop>
vnoremap <up> <nop>
inoremap <up> <nop>
noremap <down> <nop>
nnoremap <down> <nop>
vnoremap <down> <nop>
inoremap <down> <nop>
noremap <left> <nop>
nnoremap <left> <nop>
vnoremap <left> <nop>
inoremap <left> <nop>
noremap <right> <nop>
nnoremap <right> <nop>
vnoremap <right> <nop>
inoremap <right> <nop>

" delete trailing spaces
nmap _$ :call Preserve("%s/\\s\\+$//e")<CR>
" retab!!
nmap <LEADER><TAB> :call Preserve("retab")<CR>
nmap <F9> :call FormatHTML()<CR>
nmap _= :call Preserve("normal gg=G")<CR>

" no autodindent with F2
set pastetoggle=<F2>

" gidt to insert timestamp
nmap gidt a<C-R>=strftime("%Y-%m-%d %H:%M")<CR><Esc>
imap gidt <C-R>=strftime("%Y-%m-%d %H:%M")<CR>

" gid to insert date
nmap gid a<C-R>=strftime("%Y-%m-%d")<CR><Esc>
imap gid <C-R>=strftime("%Y-%m-%d")<CR>

" =============================================================================
" Filetypes and Custom Autocmds {{{1
" =============================================================================

" Tabs for various file types.
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype python setlocal ts=4 sw=4 expandtab
autocmd Filetype php setlocal ts=4 sw=4 expandtab
autocmd Filetype css setlocal ts=2 sw=2 expandtab
autocmd Filetype scss setlocal ts=2 sw=2 expandtab
autocmd Filetype snippets setlocal ts=4 sw=4 expandtab
autocmd Filetype markdown,mkd,md setlocal ts=4 sw=4 expandtab
autocmd Filetype perl setlocal ts=4 sw=4 expandtab
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0
autocmd FileType calendar set noexpandtab shiftwidth=8 softtabstop=0

augroup go
  autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
  autocmd FileType go set listchars=tab:\ \ 
augroup END

au BufRead,BufNewFile *.php set ft=html.php
au BufRead,BufNewFile *.py set ft=python
au BufRead,BufNewFile *.scss set ft=css
au BufRead,BufNewFile *.jira set ft=jira
au BufRead,BufNewFile *.rb set ft=ruby.chef
au BufRead,BufNewFile */cloudformation/**/*.yml,*/cloudformation/**/*.yaml set ft=yaml.cloudformation

"Spelling
autocmd FileType gitcommit,mail,md,markdown,mkd,jira,tex,vimwiki set spell

" Grep quickfix
autocmd QuickFixCmdPost *grep* cwindow

"Markdown files textwidth
augroup markdown
  au BufRead,BufNewFile *.md setlocal textwidth=79
  au FileType markdown setlocal textwidth=79
  au FileType markdown setlocal conceallevel=2
augroup END

" LaTeX
au BufRead,BufNewFile *.tex setlocal textwidth=79
" autocmd FileType tex setlocal makeprg=pdflatex\ '%'

" Comments
autocmd FileType gitcommit set commentstring=#\ %s

" Completion
" set omnifunc=syntaxcomplete#Complete
" autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
" autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
" autocmd FileType php setlocal omnifunc=phpcomplete#CompletePHP


" If you prefer the Omni-Completion tip window to close when a selection is
" " made, these lines close it on movement in insert mode or when leaving
" " insert mode
"autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" =============================================================================
" Plugin Settings and Mappings {{{1
" =============================================================================

xnoremap gs :sort<ENTER>

" vim-lsp
let g:lsp_settings_global_settings_dir = expand("~/.vim/")
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_semantic_enabled = 1
" Turn these off for vim-lsp
let g:go_code_completion_enabled = 0
let g:go_diagnostics_enabled = 0
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'allowlist': ['*'],
    \ 'priority': 10,
    \ 'completor': function('asyncomplete#sources#file#completor')
    \ }))

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> gi <plug>(lsp-implementation)
  nmap <buffer> gt <plug>(lsp-type-definition)
  nmap <buffer> [g <Plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <Plug>(lsp-next-diagnostic)
  nmap <buffer> K <plug>(lsp-hover)
  nmap <buffer> ca <Plug>(lsp-code-action-float)

  " nnoremap <buffer> gQ :<C-u>LspDocumentFormat<CR>
  " vnoremap <buffer> gQ :LspDocumentRangeFormat<CR>
  " nnoremap <buffer> <leader>cl :LspCodeLens<CR>
  " autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
  " autocmd! BufWritePre *.ts,*.tsx call execute('LspDocumentFormatSync --server=efm-langserver')

  nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
  nnoremap <buffer> <expr><c-d> lsp#scroll(-4)
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

highlight LspSemanticTypeDeprecated ctermfg=DarkMagenta

" ALE
let g:ale_fix_on_save = 1
let g:ale_fixers = {
  \   'python': [
  \       'black',
  \       'autoflake',
  \   ],
  \   'json': [
  \       'prettier',
  \   ],
  \}

let g:ale_floating_preview = 1
let g:ale_set_balloons = 1
let g:ale_hover_cursor = 1
" let g:ale_virtualtext_cursor = 2
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_virtualtext_prefix = "> "
let g:ale_python_autoflake_use_global = 1
let g:ale_python_pylsp_use_global = 1
" highlight ALEWarning ctermfg=DarkYellow
" highlight ALEError ctermfg=DarkMagenta
highlight ALEVirtualTextError ctermfg=DarkMagenta
highlight ALEVirtualTextWarning ctermfg=DarkYellow
" let g:ale_cursor_detail = 1
" let g:ale_close_preview_on_insert = 1
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
" set completeopt=menu,menuone,preview,noselect,noinsert
" set omnifunc=ale#completion#OmniFunc
" let g:ale_completion_autoimport = 1


let g:ale_linters = {
      \'go': ['vim-lsp'],
      \'python': ['vim-lsp'],
      \'sh': ['vim-lsp'],
      \'json': ['vim-lsp'],
      \}


let g:ale_fix_on_save_ignore = ['autopep8']

" netrw
" open from current directory
" nnoremap <leader>n :call VexToggle(getcwd())<CR>
" let g:netrw_liststyle= 3
" open from current file
" nnoremap <leader>n :call VexToggle("")<CR>

" Toggler
:nnoremap <F8> :Toggle<CR>
let g:toggler_keywords = [
  \ ['TODO', 'DOING', 'DONE'],
  \ ['True', 'False'],
  \ ['YES', 'NO'],
  \ ['\[ \]', '\[x\]'],
  \ ['x', '/'],
  \]

" vim-go plugin settings

" Regular vim-go settings
let g:go_fmt_command = "goimports"
let g:go_rename_command = "gopls"
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_auto_type_info = 1
let g:go_doc_balloon = 1
let g:go_doc_popup_window = 1
let g:go_metalinter_command = "golangci-lint"
autocmd FileType go nmap <leader>t <Plug>(go-test)
autocmd FileType go nmap <leader>b <Plug>(go-build)
autocmd FileType go nmap <leader>c <Plug>(go-coverage-toggle)
autocmd FileType go nmap <leader>e <Plug>(go-decls)
autocmd FileType go nmap <leader>w <Plug>(go-decls-dir)
autocmd FileType go nmap <leader>r <Plug>(go-def)
autocmd FileType go nmap gie <Plug>(go-iferr)
autocmd FileType go imap gie <ESC><Plug>(go-iferr)2kA
autocmd FileType go nmap <silent> <Leader>i <Plug>(go-doc)

" fzf
nmap <Leader>l :Buffers<CR>
nmap <Leader>f :GFiles<CR>
nmap <Leader>g :GFiles?<CR>
nmap <Leader>d :Files<CR>
nmap <Leader>k :call Wiki()<CR>

" vim-autoformat
noremap <F3> :Autoformat<CR>

" tmux-navigator
let g:tmux_navigator_no_mappings = 1
nmap <silent> <C-w>h :TmuxNavigateLeft<cr>
nmap <silent> <C-w>j :TmuxNavigateDown<cr>
nmap <silent> <C-w>k :TmuxNavigateUp<cr>
nmap <silent> <C-w>l :TmuxNavigateRight<cr>

" easier window navigation with ctrl pressed
nmap <silent> <C-w><C-h> :TmuxNavigateLeft<cr>
nmap <silent> <C-w><C-j> :TmuxNavigateDown<cr>
nmap <silent> <C-w><C-k> :TmuxNavigateUp<cr>
nmap <silent> <C-w><C-l> :TmuxNavigateRight<cr>

" =============================================================================
" Wiki and calendar {{{1
" =============================================================================
let g:text_dir = '$HOME/txt/'
let g:journal_dir = g:text_dir . 'journal/'
nnoremap <leader>w :e $HOME/txt/index.md<cr>
nnoremap <leader>w<leader>c :e +/<C-R>=strftime("%Y-%m-%d")<CR> $HOME/txt/calendar/2021.txt<CR>
nnoremap <leader>w<leader>j :call OpenJournalDate()<CR>
nnoremap <leader>w<leader>y :call OpenJournalDate("yesterday")<CR>
nnoremap <leader>w<leader>l :call AddLink()<CR>
" Next markdown link
nnoremap <tab> :call SearchMarkdownLink('s', 1)<CR>
" Previous markdown link
nnoremap <s-tab> :call SearchMarkdownLink('bs', 1)<CR>

autocmd FileType markdown nmap <buffer> <Enter> <Plug>Markdown_EditUrlUnderCursor

augroup textcal
  autocmd BufRead,BufNewFile */txt/calendar/* set filetype=textcal
  autocmd BufRead,BufNewFile */txt/calendar/* set spell
  autocmd BufRead,BufNewFile */txt/calendar/* set hlsearch
  autocmd BufRead,BufNewFile */txt/calendar/* exe '/'.strftime("%Y-%m-%d")
  autocmd Filetype textcal setlocal ts=16 sw=16 expandtab
augroup END

" let lspServers = [
"     \     {
"     \       'filetype': ['go', 'gomod'],
"     \       'path': '/Users/edwardlarkey/git/go/bin/gopls',
"     \       'args': []
"     \     },
"     \     {
"     \       'filetype': ['python'],
"     \       'path': '/usr/local/bin/pyls',
"     \       'args': []
"     \     },
"     \   ]
" call LspAddServer(lspServers)

" Markdown
let g:vim_markdown_folding_disabled = 1

" Check for local settings for env specific settings. e.g. Work specific
" config
"
if !empty(glob("~/.local.vimrc"))
  source ~/.local.vimrc
endif
