#! /bin/sh

bspc config border_width        0
bspc config window_gap         20

bspc config top_padding			20
bspc config right_padding		5
bspc config bottom_padding	5
bspc config left_padding		5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -n 0 -d  I II III
bspc monitor DVI-I-1 -n 1 -d IV V VI VII

bspc rule -a Chromium desktop=^1
bspc rule -a HipChat desktop=^6
bspc rule -a Spotify desktop=^3

$HOME/.config/bspwm/panel/panel &

compton -b

redshift -l 38.881126:-94.821048

feh --bg-scale ~/Dropbox/wallpaper/current.jpg

