# Change the directories to set wallpapers;:
preload = ~/dotfiles/wallpaper/wallpaper.png

# Make sure to also set the correct monitors (hyprctl monitors)
wallpaper = DP-2,~/dotfiles/wallpaper/wallpaper.png
