#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!MONITORS!!                                   #

# Make sure to customize monitors! This is just my setup so you get an idea.
# run `hyprctl monitors all` to see all your monitors!!!
# monitor=DP-2, 1920x1080@144.00, 0x250, 1
monitor=eDP-1, 2560x1440@60.0.1200, 0x0, 1.3333334

# Startup programs, these are mine, most likely you'll have these as well.
# exec-once = nm-applet
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- hyprsunset
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar
# exec-once = quickshell
# exec-once = uwsm app -- walker --gapplication-service
# exec-once = uwsm app -- elephant
# exec-once = hyprctl setcursor Hackneyed-24px 24
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data



# Default programs, these are what I prefer.
$terminal = ghostty
$fileManager = thunar
$cliFileManager = yazi
$top = btop

$menu = dmenu_path | wofi -m -I | xargs exec --


# Environment variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Don't show update on first launch
ecosystem {
  no_update_news = true
}


input {
    kb_layout = us
    kb_options = ctrl:nocaps

    # Set as needed
    kb_rules = 
    kb_variant =
    kb_model =

    repeat_delay = 200
    repeat_rate = 40

    follow_mouse = 1

    # Range is -1.0 to 1.0 | 0 means no modification to sensitivity.
    sensitivity = 0 

    touchpad {
        natural_scroll = true
    }

}

device {
  name = logitech-ergo-m575
  scroll_method = on_button_down
  scroll_button = 276
}

# This fixes a few bugs.
cursor {
  no_hardware_cursors = true
}

gestures {
  gesture = 3, horizontal, workspace
  workspace_swipe_create_new = false
  workspace_swipe_distance = 200
}

source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/windows.conf
