<<<<<<< HEAD
||||||| parent of 4777c10 (Changes from kompot)
#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!MONITORS!!                                   #

# Make sure to customize monitors! This is just my setup so you get an idea.
# run `hyprctl monitors all` to see all your monitors!!!
# monitor=DP-2, 1920x1080@144.00, 0x250, 1
# monitor=eDP-1, 2560x1440@60.0.1200, 0x0, 1.3333334
source = ~/.local.monitors.conf

# Startup programs, these are mine, most likely you'll have these as well.
# exec-once = nm-applet
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = mako
exec-once = waybar
exec-once = hypridle
# exec-once = quickshell
# exec-once = hyprctl setcursor Hackneyed-24px 24
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
=======
#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!MONITORS!!                                   #

# Make sure to customize monitors! This is just my setup so you get an idea.
# run `hyprctl monitors all` to see all your monitors!!!
# monitor=DP-2, 1920x1080@144.00, 0x250, 1
# monitor=eDP-1, 2560x1440@60.0.1200, 0x0, 1.3333334
source = ~/.local.monitors.conf

# Startup programs, these are mine, most likely you'll have these as well.
# exec-once = nm-applet
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = mako
exec-once = waybar
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
>>>>>>> 4777c10 (Changes from kompot)


# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

autogenerated = 1

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
