# wallpaper {
#   monitor = 
#   path = ~/dotfiles/wallpaper/wallpaper.png
#   fit_mode = cover
# }

wallpaper {
  monitor = 
  path = ~/dotfiles/wallpaper/OS9_Default.png
  fit_mode = tile
}

splash = false
