-- OS 99 – generated by dotfiles/setup. Safe to delete.
-- Source this from your main hyprland.lua:
--   dofile(os.getenv("HOME") .. "/.config/hypr/os99.lua")

local home = os.getenv("HOME")
local os99_share = (os.getenv("XDG_DATA_HOME") or (home .. "/.local/share")) .. "/os99"
local os99_bin   = home .. "/.local/bin"

os99_dir = os99_share .. "/decor"

if os99_dir and io.open(os99_dir .. "/bars.lua", "r") then
  dofile(os99_dir .. "/bars.lua")
end

