[Gmail]
from                    = Edward Larkey <edwlarkey@gmail.com>
source                  = imaps://edwlarkey%40gmail.com@imap.gmail.com:993
outgoing                = smtps://edwlarkey%40gmail.com@smtp.gmail.com
default                 = INBOX
folders-sort            = INBOX
postpone                = [Gmail]/Drafts
cache-headers           = true
copy-to                 = Sent
source-cred-cmd         = pass mail/gmail/aerc
outgoing-cred-cmd       = pass mail/gmail/aerc
carddav-source          = https://edwlarkey%40gmail.com@www.googleapis.com/carddav/v1/principals/edwlarkey@gmail.com/lists/default
carddav-source-cred-cmd = pass mail/gmail/aerc
address-book-cmd        = carddav-query -S edwlarkey %s

[.mac]
source        = imaps://edwlarkey%40mac.com@imap.mail.me.com:993
outgoing      = smtps://edwlarkey%40mac.com@smtp.mail.me.com:587
default       = INBOX
from          = Edward Larkey <edwlarkey@mac.com>
copy-to       = Sent Messages
cache-headers = true
source-cred-cmd         = pass mail/mac/aerc
outgoing-cred-cmd       = pass mail/mac/aerc
