# Zshrc

[ -e "${HOME}/.zsh/alias.zsh" ] && source "${HOME}/.zsh/alias.zsh"
[ -e "${HOME}/.local.zsh" ] && source "${HOME}/.local.zsh"


source "$HOME/.zsh/antigen/antigen.zsh"

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundle git
antigen bundle mercurial
antigen bundle pip
antigen bundle rsync
antigen bundle python
antigen bundle tmux

if [ "$OSTYPE"="darwin11.0" ]; then
  antigen bundle osx
fi

antigen bundle vagrant
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen theme "$HOME/.zsh/themes/edwlarkey"  --loc=edwlarkey --no-local-clone

antigen-apply



