# Zshrc
# Defines environment variables

#
# Basic Config
#

ZDOTDIR=${ZDOTDIR:-${HOME}}
ZSHDIR="${HOME}/.zsh"
HISTFILE="${ZDOTDIR}/.zsh_history"
HISTSIZE='10000'
SAVEHIST="${HISTSIZE}"


setopt append_history
setopt extended_history
setopt inc_append_history
setopt extended_glob
setopt extended_history
setopt complete_in_word
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_verify
setopt hist_allow_clobber

#
# Autoloads and bindings
#
# Command line edit in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# ZSH settings
autoload -U url-quote-magic
zle -N self-insert url-quote-magic


#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi
export LANG='en_US.UTF-8'

#
# Go
#
export GOPATH=$HOME/git/go
export GOBIN=$GOPATH/bin

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $GOBIN
  /usr/local/opt/coreutils/libexec/gnubin
  /usr/local/{bin,sbin}
  $path
)

MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# TERM
export TERM=xterm-256color

#
# Source aliases
#
[ -e "${HOME}/.zsh/alias.zsh" ] && source "${HOME}/.zsh/alias.zsh"

if type setxkbmap >/dev/null 2>&1; then
  setxkbmap -option ctrl:nocaps
fi

# Custom completion scripts
fpath=(~/.zsh/completion $fpath)

# Completion.
autoload -Uz compinit
compinit -U
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:descriptions' format '%U%F{cyan}%d%f%u'


# Modules
source "${ZSHDIR}/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "${ZSHDIR}/modules/zsh-history-substring-search/zsh-history-substring-search.zsh"

## Module config
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=magenta,fg=white,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=red,fg=white,bold'
HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS='i'
# bind UP and DOWN keys
bindkey "${terminfo[kcuu1]}" history-substring-search-up
bindkey "${terminfo[kcud1]}" history-substring-search-down
# bind UP and DOWN arrow keys (compatibility fallback)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Prompt
source "${ZSHDIR}/themes/edwlarkey/edwlarkey.zsh-theme"

export LSCOLORS='exfxcxdxbxGxDxabagacad'
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=32:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:'

GPG_TTY=$(tty)
export GPG_TTY

# Source any local zsh configuration
[ -e "${HOME}/.local.zsh" ] && source "${HOME}/.local.zsh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault

tmux new-session -A -s org
